package com.ob.broker.common.event;

public enum EventType {
    LOGON, CONNECT, DISCONNECT, RECONNECT, TEST, PING, PONG, INSTRUMENT_NOT_FOUND, BROKEN_CHANNEL, PRICE, OPEN_ORDER, CLOSE_ORDER, PENDING_ORDER, OPEN_PARTIAL_ORDER, CLOSE_PARTIAL_ORDER, CANCEL_ORDER, FILL_PENDING_ORDER, REJECT_ORDER, UPDATE_PENDING_ORDER, UPDATE_ORDER, UPDATE_ACCOUNT, LOAD_USER, LOAD_INSTRUMENT, LOAD_ACCOUNT, LOAD_HISTORY, LOAD_OPEN, LOAD_PENDING, LOAD_CLOSE, SUBSCRIBE, INFO, REQUEST;
}
